import { Query } from "./query";
import { Sort } from "./sort";
import { Sequelizable } from "./sequelize";
import { Rule } from "./rule";
import { Cloneable } from "./cloneable";
export declare class Filter implements Sequelizable, Cloneable<Filter> {
    context: {};
    queryGroup: Query[];
    sortBy: Sort[];
    queryGroupMergeOperator: string;
    static merge(filters: Filter[]): Filter;
    static build(filter: any): Filter;
    constructor(queryGroup?: Query[], sortBy?: Sort[]);
    setTableDefinition(tableDefinition: any): void;
    isEmpty(): boolean;
    hasEmptyQueryGroup(): boolean;
    hasEmptySortCondition(): boolean;
    hasInValidSortCondition(): boolean;
    checkValidSortCondition(): boolean;
    hasEmptyRules(): boolean;
    hasInvalidRules(): boolean;
    hasDynamicVariables(): boolean;
    unsequelize(sequelized: any): this;
    sequelize(): {};
    sequelizeString(): string;
    clone(): Filter;
    toString(): string;
    stringify(): string;
    getAllRules(): Rule[];
    removeRule(rule: Rule): void;
    reset(): void;
}
